### ISSUE TITLE
[Request] Porting some patches for getting great performance #1

### ISSUE THREAD

**Issue by NovaPixell** [etil2jz/Mirai#1]
Hi, this is an interesting fork! 

These patches are:

1. https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.5/patches/server/0016-Heavily-optimize-furnance-fuel-and-recipe-lookups.patch
2. https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.5/patches/server/0039-Heavily-optimize-recipe-lookups-in-CraftingManager.patch
3. https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.5/patches/server/0065-lithium-skip-ticking-block-entities-that-are-doing-n.patch

The third patch is very useful for servers that have high amounts of TE.

Please consider importing these patches, as a performance boost can be achieved

**Comment by etil2jz** [comment]
Hi, first thank you for your interest in my fork.

My schedule does not currently allow me to work on my personal projects, but I'm putting this request aside and will process it when I have the opportunity.

**Comment by etil2jz** [comment]
For the two first patches, the fuel and recipe systems are different in 1.17/1.18, and they don't need to be ported.

The third one can't be considered safe as it may enter in conflict with Bukkit patches…
