### ISSUE TITLE
Error saving world

### ISSUE THREAD

**Issue by ghost** [etil2jz/Mirai#14]
![image](https://user-images.githubusercontent.com/68630033/158021098-0b0b02e9-d0a2-4b52-b322-66d7681a7495.png)
Even if there is no plugin, a save error will occur when the player closes the server after entering, which will cause the player to revert. The latest build of Mirai is used.

**Comment by etil2jz** [comment]
Hi, thanks for your report.
Can you try reproduce this issue on a fresh server / a different system?

**Comment by Dreeam-qwq** [comment]
same error, but player data will not revert on my server.

**Comment by ghost** [comment]
> Hi, thanks for your report. Can you try reproduce this issue on a fresh server / a different system?

Sorry, it is probably impossible for me to switch the system test here, but I tried the server without plugins again. If no player joins, there is no problem with closing the server. If there is a player joining, closing the server will show an error message about saving playerdata

**Comment by etil2jz** [comment]
Can you try reproducing this error with latest build b1a66f8?
I can not reproduce this on my side.

**Comment by ghost** [comment]
> Can you try reproducing this error with latest build [b1a66f8](https://github.com/etil2jz/Mirai/commit/b1a66f86f64ec142035c632d10d6d184c5b779fc)? I can not reproduce this on my side.

I'm sorry to trouble you. In my later tests, the situation that saving the map archive will return the file with an error has never appeared again, and I don't know how it disappeared. But still thank you for your help, thanks
