### ISSUE TITLE
piglin AI lost | 猪灵AI丢失

### ISSUE THREAD

**Issue by stevesensei** [etil2jz/Mirai#15]
你好,我是用mirai的1.18.2版本最新构建来开服游玩,但是我进入地狱以后发现,猪灵和猪灵蛮兵的AI丢失,不会主动攻击,猪灵交易会卡在看金锭那一个环节,但是我换用paperspigot以后问题解决
以及地牢的生成在1.18.2单机里输入同样的种子,使用chunkbase查找地牢,位置是正确的,但是同样的位置服务器却没有,经查证地牢的生成仍停留在1.17,我不知道这是不是服务端的问题
谢谢

Hello,I'm using mirai 1.18.2 the latest build for server,But when I went to nether,I found that piglin and Piglin Brute's AI lost,they don't attact activly.The piglin deal is stuck,But when I change to paperspigot,the problem solved
And when I use the same seed to create a world in singleplay,using chunkbase to find stronghold,position is right,I can find it in single play,But server not(It's new world,not update from 1.17),I don't know if it's mirai's problem
that's all,thanks

**Comment by elpixis** [comment]
Possibly to greatly improve performance Mirai had to sacrifice some functions of vanilla minecraft, it is very likely that your "problem" is caused by mirai, if you are not willing to sacrifice performance for functions you should not use a fork.

**Comment by stevesensei** [comment]
Ok...If it's mirai's bug,just fix it.Thanks
