### ISSUE TITLE
Could you publish the jar in another way?

### ISSUE THREAD

**Issue by Mhy278** [etil2jz/Mirai#16]
As a Mirai user, I really like Mirai, which is why I say this.
Please forgive me, the current jar release method is really inconvenient! 
The current action configuration is very troublesome for version management and download. Maybe you do this for your own reasons, I understand what you are doing very well, but as a normal user, I still make such a suggestion, thank you anyway.

**Comment by ghost** [comment]
What do you mean by "publish the jar in a another way"?

**Comment by Mhy278** [comment]
I think it would be better if action bot draft a release automatically instead of pushing them into the build repos.

**Comment by ghost** [comment]
Yes, it would be convenient to have a page on codemc

**Comment by Mhy278** [comment]
Yes you are right, codemc is also a way.

**Comment by etil2jz** [comment]
I made a request to have access to CodeMC's CI 🤞

**Comment by 4o3F** [comment]
Why not just use Github's Release?

**Comment by ghost** [comment]
Personally, I don't feel comfortable downloading. On CodeMC you can immediately view the history of builds. Well, yeah ;)

**Comment by etil2jz** [comment]
Mirai builds are now pushed in GitHub's Release. I don't close this issue as my goal is to have a CI server.

**Comment by ghost** [comment]
Etil, any progress with the CodeMC ?

**Comment by etil2jz** [comment]
@F1rsi No answer yet

**Comment by ghost** [comment]
Bad news :(

**Comment by ghost** [comment]
Close this issue

**Comment by etil2jz** [comment]
https://ci.codemc.io/job/etil2jz/job/Mirai-1.19/
