### ISSUE TITLE
[Patch Request] Purpur Sign Patches

### ISSUE THREAD

**Issue by NovaPixell** [etil2jz/Mirai#2]
These patches:

https://github.com/pl3xgaming/Purpur/blob/ver/1.17.1/patches/server/0046-Signs-allow-color-codes.patch

https://github.com/pl3xgaming/Purpur/blob/ver/1.17.1/patches/server/0045-Signs-editable-on-right-click.patch

For perms: https://github.com/pl3xgaming/Purpur/blob/ver/1.17.1/patches/api/0004-Default-permissions.patch

**Comment by etil2jz** [comment]
My schedule does not currently allow me to work on my personal projects, but I'm putting this request aside and will process it when I have the opportunity.

**Comment by etil2jz** [comment]
I'll publish a build tomorrow, for the moment you need to compile it yourself.
