### ISSUE TITLE
When I use velocity, I can't join the server anyway.

### ISSUE THREAD

**Issue by TH2403y** [etil2jz/Mirai#20]
Even if I use the 1.18.2 client, he will prompt [Outdated client Please use 1.18.2
![~W4PM_WIAA9)%%O`O0C6ZUO](https://user-images.githubusercontent.com/86739442/161411616-b534e9ab-43d7-40da-af70-9cfe5b8e82c2.png)
]

**Comment by 4o3F** [comment]
I'm using Velocity too, I don't experience any issues

**Comment by ghost** [comment]
I'm using Velocity too, I don't experience any issues

**Comment by etil2jz** [comment]
I'm closing this issue as it looks like a configuration error on your side.
