### ISSUE TITLE
Portal loop with installed MyWorlds plugin

### ISSUE THREAD

**Issue by lynrayy** [etil2jz/Mirai#23]
In survival mode, you will stuck in nether portal teleportation loop if you use MyWorlds plugin for multiverse. To fix it (looping), set player-fix-stuck-in-portal: *** to FALSE

ironic issue

**Comment by etil2jz** [comment]
Kinda ironic indeed, but it means the problem can be reproduced on Purpur with this config option enabled.
I should set it to false by default if more plugins do have the same issue.
