### ISSUE TITLE
请问可以关闭ＧＵＩ吗，让服务器终端运行在ＤＯＳ窗口中

### ISSUE THREAD

**Issue by GoaTham** [etil2jz/Mirai#27]
启动参数中加上－ｎｏｇｕｉ也没用，并且还有一个问题，关闭服务器后后台的服务器进程不会自动消失　需要去任务管理器手动结束一下

**Comment by ghost** [comment]
Try using "nogui" instead of "-nogui" at the end of your server startup

**Comment by GoaTham** [comment]
I tried "nogui" "-nogui" "--nogui" but it was useless

Mirai: latest build
Java Version:jdk-17.0.3.1
MineCraft Version:1.18.2
The startup parameter I used: "d:\software\java\jdk-17.0.3.1\bin\javaw.exe" -jar mirai-paperclip-1.18.2-r0.1-snapshot-reobf jar nogui

**Comment by ghost** [comment]
You misspelled the start command because you left out the "." after "reobf" in the JAR file name. Try the following: d:\software\java\jdk-17.0.3.1\bin\javaw.exe" -jar mirai-paperclip-1.18.2-r0.1-snapshot-reobf.jar nogui

**Comment by GoaTham** [comment]
Sorry, actually, my startup parameters are like this
(d:\software\java\jdk-17.0.3.1\bin\javaw.exe" -jar mirai-paperclip-1.18.2-r0.1-snapshot-reobf.jar nogui)

But because I used the translation software and didn't check it carefully, it became like this
(d:\software\java\jdk-17.0.3.1\bin\javaw.exe" -jar mirai-paperclip-1.18.2-r0.1-snapshot-reobf jar nogui)

**Comment by ghost** [comment]
Why do you only have one double quote? Could that be the mistake?

**Comment by etil2jz** [comment]
Did you try using `java.exe` instead of `javaw.exe`?

**Comment by GoaTham** [comment]
Translation software can cause this problem   (owo)

It's actually two double quotes.

**Comment by GoaTham** [comment]
VeryGood!!!

I try to use java.exe, this problem has been solved. Thank you very much for your help. I wish you a happy life
