### ISSUE TITLE
Long loading of chunks when using data packs for world generation

### ISSUE THREAD

**Issue by DonorKrovi** [etil2jz/Mirai#28]
![image](https://user-images.githubusercontent.com/60231586/171569549-2e1abce4-eaee-49bc-a954-3f9a28699c7c.png)
[archive-2022-06-02T082926+0200.tar.gz](https://github.com/etil2jz/Mirai/files/8821365/archive-2022-06-02T082926%2B0200.tar.gz) My datapacks

For example, I teleported to large coordinates and loaded 1 chunk into them, saw a burst of TPS drop and then after a while the chunks loaded, but when I generate them further they just freeze and slowly continue to display themselves
![image](https://user-images.githubusercontent.com/60231586/171569998-a2f4005c-b2ed-4d65-8f03-6282aad1fb5d.png)

**Comment by en0tuk** [comment]
Mirai version?

**Comment by DonorKrovi** [comment]
Last 1.18.2-purpur

**Comment by ghost** [comment]
Timings?

**Comment by DonorKrovi** [comment]
overload node (Hosting)
