### ISSUE TITLE
Villager & Monsters are despawned if the player next to them goes into spectator mode

### ISSUE THREAD

**Issue by ghost** [etil2jz/Mirai#31]
I checked this bug on the following versions:
  Purpur build 1632
  Mirai Pufferfish 1.18.2 #807ee9c
  Mirai Purpur 1.18.2 #bbbb202

As a result, I got the following results, where Yes = bug exist, No = no bug

Mirai Pufferfish 1.18.2 #807ee9c: Yes
Mirai Purpur 1.18.2 #bbbb202: Yes
Purpur 1.18.2 build 1632: No

**Comment by minhh2792** [comment]
This patch likely to cause this problem, I dropped it on my personal fork and it's fixed

https://github.com/etil2jz/Mirai/blob/ver/1.18.2/patches/server/0049-PaperPR-Optimize-despawn-when-no-player-is-on-range.patch

**Comment by etil2jz** [comment]
Yep, I identified it a bit earlier. I'm going to drop it and reorganize patches.

**Comment by ghost** [comment]
@minhh2792 Is your fork private?
