### ISSUE TITLE
What is the stability of Mirai? Is it suitable for use in the formal environment?

### ISSUE THREAD

**Issue by cnluminous** [etil2jz/Mirai#33]

**Comment by ghost** [comment]
Core is stable in principle, but read the project description before using

**Comment by cnluminous** [comment]
OK. When will Mirai be updated to 1.19? Very much expected :)

**Comment by ApliNi** [comment]
This may take a while as there is a lot of upstream software )

**Comment by ghost** [comment]
@cnluminous close this issue
