### ISSUE TITLE
Server JVM crash

### ISSUE THREAD

**Issue by sensen1234** [etil2jz/Mirai#34]
Mirai-purpur latest version, 1.18.2

Server crashes from time to time, Alibaba_for Java Dragonwell_ 17.0.3.0.3+7

Server version winserver2016 plugins have been checked and should be OK

The log is as follows (There is also an 8g MDMP file which is not easy to send)
[hs_err_pid42276.log](https://github.com/etil2jz/Mirai/files/9032812/hs_err_pid42276.log)

Original:

mirai-purpur最新版，1.18.2
服务器时不时崩溃，java用的Alibaba_Dragonwell_17.0.3.0.3+7
服务器版本winserver2016 插件已排查过，应该是没有问题
日志如下（还有一个大小8g的mdmp文件，不方便发）

https://t.wss.ink/f/8p9qbg2ip57

**Comment by etil2jz** [comment]
From the crash log, it's an issue from your Windows server. You should try with Linux, 99% sure this error won't appear on it.

**Comment by ghost** [comment]
@sensen1234 Have you tried what Etil recommended?

**Comment by etil2jz** [comment]
No answer
