### ISSUE TITLE
Hoglin Problem

### ISSUE THREAD

**Issue by MineSunshineone** [etil2jz/Mirai#35]
Hoglin will stay away from The Strange Bacteria, Strange Mushroom Potted Plants, Nether Portal Blocks, and Respawn Anchors 7 blocks

But it dont work on the mirai lastest ver 

This server is running Mirai version git-Mirai-64a31b5 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 64a31b5 on ver/1.19)

![19D090AD3FB774B7F8AA2B225187304E](https://user-images.githubusercontent.com/107391209/177024088-065c1d26-8e0b-4995-b9d3-c5fd3acdf02c.png)

**Comment by ghost** [comment]
Update to the latest version and this problem should go away.

**Comment by ghost** [comment]
It's only a problem on your side. Why? Because I just downloaded the kernel version on which you noticed the wrong behavior and with the standard configs everything works fine

**Comment by ghost** [comment]
Etil close this issue

**Comment by MineSunshineone** [comment]
> 

最新的Mirai已经更新了吗

**Comment by ghost** [comment]
Pufferfish version yes. Use only english plz

**Comment by MineSunshineone** [comment]
> 河豚版是的。请仅使用英语

ok thanks
