### ISSUE TITLE
Network problem 

### ISSUE THREAD

**Issue by MineSunshineone** [etil2jz/Mirai#37]
Brief introduction：
I drive a 50-person daily active server, but I'm distressed that many players don't have high latency, but often drop the line
At first I thought that this option was not turned on, but he had already turned it on, and I found that after turning off this option, there were fewer abnormal drops 
So,i close it  "use-alternate-keepalive: false" （In Timings ) 
I would like to ask why this option is not useful, and the chance of letting the line drop increase, can you check the patch?

![94AA7C06BD930F37D5AB7DC513FB760D](https://user-images.githubusercontent.com/107391209/178265064-d0db893b-0f9c-4bca-87e2-97687ffe2359.png)

Ver ：This server is running Mirai version git-Mirai-28d706c (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 28d706c on ver/1.19)

Config：https://timings.aikar.co/?id=97282b895319403baa17e06a75616ee1

**Comment by MineSunshineone** [comment]
If you still need any information please ask me

**Comment by ghost** [comment]
What exactly happened to you? Most of your players can't join the server or they get kicked when the ping is high?

**Comment by MineSunshineone** [comment]
Players can join the server normally, but some players with a ping of less than 50ms will drop the line, and most of them

**Comment by ghost** [comment]
Can you send mirai.yml ?

**Comment by MineSunshineone** [comment]
[mirai.txt](https://github.com/etil2jz/Mirai/files/9091692/mirai.txt)

**Comment by MineSunshineone** [comment]
"use-alternate-keepalive: false" help a lot

**Comment by ghost** [comment]
Can you try Pufferfish?

**Comment by MineSunshineone** [comment]
i try it so i think maybe the problem in Mirai

**Comment by MineSunshineone** [comment]
may in this patch "use-alternate-keepalive：false"

**Comment by etil2jz** [comment]
The patch is the exact copy of Purpur one. Test with Purpur.
