### ISSUE TITLE
[Feature Request] Pretty configuration file.

### ISSUE THREAD

**Issue by ghost** [etil2jz/Mirai#41]
I don't understand MiraiConfig.java, so I will write here

To simplify working with the configuration file, I wanted to implement copying the file mirai.yml from the configurations folder, where bukkit.yml, commands.yml are located

Here is the file itself: https://pastebin.com/2K6sS0MR

**Comment by etil2jz** [comment]
I don't understand what you want to achieve

**Comment by ghost** [comment]
I originally edited mirai.yml to make the file a little prettier. Then I wanted to make changes in MiraiConfig.java to make all the changes take effect, but I didn't figure it out. In addition, I wanted to make it easier to install the config for mintcraft servers, not by gradually assembling the Yaml file, but by simply copying the file from one location to another.
