### ISSUE TITLE
JVM Crash when generating new chunks

### ISSUE THREAD

**Issue by Hapixs** [etil2jz/Mirai#46]
Hi, I juste dicoverd and tested Mirai, It seam pretty good for the server performances in general until I try chunky to check the chunk load rate.

For the first time I use Chunky with Mirai the server crashed. So to be sure it was chunk generation I walked far from my pregenerate zone and when entering the non generated zone the server crashed the same way, I also try to teleport myseft realy far and same crash.

I got a lot of thread dump but there is the last one I got (from teleporting)
- https://pastebin.com/LBEqH8iw

Last logs before crash:
- https://pastebin.com/7j6xsZg6

I used the last release of Mirai (1.19) with TEMURIN 18 and the JVM Flags on the git repo https://github.com/etil2jz/etil-minecraft-flags

Btw Idk if its realy Mirai or my physical server but I think not.

**Comment by ghost** [comment]
Is the latest version 1.19 or 1.19.1?
It seems that flags from etil are supported on GraalVM EE

**Comment by etil2jz** [comment]
I met the same issue. Will try to diagnostic generation patches

**Comment by Hapixs** [comment]
> Is the latest version 1.19 or 1.19.1? It seems that flags from etil are supported on GraalVM EE

The last release version (Minecraft 1.19.1 sry)

**Comment by etil2jz** [comment]
Narrowed down the issue to `-XX:+UseCMoveUnconditionally` flag. Removing or disabling it should fix the JVM.

**Comment by Hapixs** [comment]
Ok it worked for me 👍 thanks
I'll do some test to check if its stable in long use
