### ISSUE TITLE
Alternate Current

### ISSUE THREAD

**Issue by comendantmc** [etil2jz/Mirai#51]
Hi, I read in the README that this fork uses Alternate Current, but I couldn't find any patches with the implementation. Was this feature removed?

**Comment by comendantmc** [comment]
nvm, I found it in the paper's patches. It is kind of strange though that this is mentioned as one of the features of this fork

**Comment by etil2jz** [comment]
It was a feature before Paper decided to merge it. It still isn't the default algorithm and Mirai sets it to default when generating files.
