### ISSUE TITLE
AsyncPlayerChatEvent issue

### ISSUE THREAD

**Issue by RanMinecraft** [etil2jz/Mirai#52]
mirai.yml
disable-chat-reports: true

Player name disappear after plugin run event.setFormat()
Message look like this...
![image](https://user-images.githubusercontent.com/69817107/183261796-e853c6bb-be23-4d26-9c5c-56432b2383f3.png)

**Comment by etil2jz** [comment]
Please add more details
Does it happen on build 18?
Does it work correctly if `disable-chat-reports: false`?

**Comment by RanMinecraft** [comment]
> Please add more details Does it happen on build 18? Does it work correctly if `disable-chat-reports: false`?

only when disable-chat-reports: true
used last build #19

**Comment by etil2jz** [comment]
Can you try with build 18, before Paper changed some chat system methods

**Comment by RanMinecraft** [comment]
It won't happen on build 18

**Comment by RanMinecraft** [comment]
Player got kicked when AsyncPlayerChatEvent cancel.

![image](https://user-images.githubusercontent.com/69817107/183262432-75fa48a0-e2b6-4451-8e86-ecadd8d43a5c.png)

![image](https://user-images.githubusercontent.com/69817107/183262388-44769aa3-8949-4856-8a78-4114a25c9f68.png)

**Comment by etil2jz** [comment]
The chat message signature patch works by converting all player messages to system messages, so they can't be reported nor will be flagged as unverified. I'm afraid that this workaround breaks the AsyncPlayerChatEvent.

I guess there must be a compromise between being able to interact with player messages and allowing report system to work as intended.

**Comment by RanMinecraft** [comment]
> The chat message signature patch works by converting all player messages to system messages, so they can't be reported nor will be flagged as unverified. I'm afraid that this workaround breaks the AsyncPlayerChatEvent.

Sounds okay to me, let's break AsyncPlayerChatEvent
