### ISSUE TITLE
fix mirai's official site

### ISSUE THREAD

**Issue by ghost** [etil2jz/Mirai#6]
Now:
![image](https://user-images.githubusercontent.com/68630033/147255928-31921774-a5d8-4d82-9671-b15ce6a51810.png)

**Comment by etil2jz** [comment]
I didn't create the website yet, but it's not a problem right now as you can download the JAR from GitHub.

**Comment by ghost** [comment]
> I didn't create the website yet, but it's not a problem right now as you can download the JAR from GitHub.

ok :)

**Comment by etil2jz** [comment]
[Website](https://etil.wtf/mirai/) is now accessible with direct links to download.
