### ISSUE TITLE
NPCs generated by citizen plugins are sometimes visible and sometimes not visible.

### ISSUE THREAD

**Issue by RangFarm** [etil2jz/Mirai#61]
There are NPCs that you can see when you reconnect, but there are still NPCs that you can't see. I am using the latest version of Mirai. NPC with type set to animal can be seen well.

**Comment by etil2jz** [comment]
This is an issue with Petal's multithreaded entity tracker (see https://github.com/Bloom-host/Petal/issues/3).
You can disable it in mirai.yml (will work) or try to use a [Citizens dev build](https://ci.citizensnpcs.co/job/citizens2/lastStableBuild/) (could work).

**Comment by RangFarm** [comment]
It's resolved! Thank you for making a good bucket

**Comment by MrButtersDEV** [comment]
> It's resolved! Thank you for making a good bucket

What option did you go with? Dev build or disabling it in the yml?

**Comment by RangFarm** [comment]
Yes, that's right! I changed it from true to false XD
