### ISSUE TITLE
Opening a naturally-generated chest with a map inside lags out the server

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [etil2jz/Mirai#63]
- Go to structures with a chest that contains a map (treasure map for example) such as shipwreck, ocean ruins
- Open the chest

The server will lag out for a bit, then back to normal. It might also kick other players and corrupt the map as well.

**Comment by QuanTrieuPCYT** [comment]
seems to be a vanilla issue as well, i'm closing this

**Comment by TerdyTheTerd** [comment]
Is there a bug tracker for this on vanilla? I have run several paper servers of recent and never had issues with maps in chest, and I obviously would not want to introduce this issue into my next server.

**Comment by QuanTrieuPCYT** [comment]
> Is there a bug tracker for this on vanilla? I have run several paper servers of recent and never had issues with maps in chest, and I obviously would not want to introduce this issue into my next server.

[MC-249136](https://bugs.mojang.com/browse/MC-249136) and [MC-218156](https://bugs.mojang.com/browse/MC-218156)
