### ISSUE TITLE
Suggestion: add an option to use /reload

### ISSUE THREAD

**Issue by NVGAT** [etil2jz/Mirai#64]
I'm aware that /reload can be a harmful command, but most of the servers that use Mirai are test or dev servers anyway (at least for now when Mirai is in its dev phase), where there's no real damage done even if something goes wrong while reloading.

**Comment by ghost** [comment]
Use PlugManX.

**Comment by etil2jz** [comment]
You can use `-Dmirai.DisableReloadCommand` in launch options
