### ISSUE TITLE
1.19.3 Support Please.

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [etil2jz/Mirai#72]
This is the most powerful Server Software I've ever used.
I like it sooooooo much , and I cannot wait the support of 1.19.3
But the developers ***stopped developing(maybe)*** after the last update on Oct 21, 2022.
I wonder what happened caused this , or maybe ***we (Users of Mirai)*** can offer some help. (such as sponsor？）
Looking forward to your reply.

**Comment by ghost** [comment]
There is only one developer - Etil. He doesn't have time.
