### ISSUE TITLE
掠夺者农场无法使用

### ISSUE THREAD

**Issue by Canary233** [etil2jz/Mirai#8]
相同存档已确认在Papar和Purpur上正常工作

**Comment by etil2jz** [comment]
I don't speak Chinese.
Can you please rephrase in English?

**Comment by Canary233** [comment]
> I don't speak Chinese. Can you please rephrase in English?

Sorry,I see "未来" in about,Thought you were from China.

**Comment by Canary233** [comment]
> I don't speak Chinese. Can you please rephrase in English?

Minecraft Elegance: Instant AFK Raid Farm, 3000+ emeralds/hr (Java 1.16-1.18)
https://www.youtube.com/watch?v=hVHFIfZAL54
https://www.bilibili.com/video/bv1864y1f7pa

This farm not work on your server software,but it can run on paper and purpur.

**Comment by Canary233** [comment]
Problem has been solved.
In pufferfish.yml
dab:
  enabled: false
